### ISSUE TITLE
Create Flight: Insert Time Now Buttons

### ISSUE THREAD

**Issue by atoff** [aliaksei135/FlightDutyTracker#4]
Would be nice to have a button beside each datetime field (Duty From/To and Flight From/To) to populate the respective field with the current time when clicked. Would mean less hassle when used.

**Comment by aliaksei135** [comment]
Clicking each of these opens the dialog to the current datetime regardless.

**Comment by atoff** [comment]
It does, but following the date picker route would require 2 taps, whereas a button would only require 1.

Small difference, but for the user it is 1) easier to confirm that clicking the button sets the current time 2) requires less clicks.

**Comment by aliaksei135** [comment]
Added! Thanks for the suggestion!
