### ISSUE TITLE
Move Marker based on Location Changed between to points

### ISSUE THREAD

**Issue by SopMar** [aliaksei135/FlightDutyTracker#5]
I have to create Moving Map like [this](http://upgrd.com/images/upload/image/aerospace/img_0139.JPG) one.

My main concern is How to update and move AIRPLANE marker based on Location changed ?

May I know What's the best way of achieving this and please share an updated code with us, so we can learn.

**Comment by aliaksei135** [comment]
This isn't (and will not be) a part FlightDutyTracker, however after 5 mins on Google...

I would use a [Ground Overlay](https://developers.google.com/maps/documentation/android-api/groundoverlay) for the departure, destination and aircraft drawables and a [polyline](https://developers.google.com/maps/documentation/android-api/shapes#polylines) for the path between the departure and destination.

**Comment by SopMar** [comment]
Thanks Pilot cum Android Master :)
